#!/bin/bash
# =============================================================
# 03-setup-env.sh — 產生 .env.prod 和 docker-compose.prod.yml
# =============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENDPOINT_FILE="${SCRIPT_DIR}/.rds-endpoint"
ENV_FILE="${PROJECT_DIR}/.env"
ENV_PROD_FILE="${PROJECT_DIR}/.env.prod"
COMPOSE_PROD_FILE="${PROJECT_DIR}/docker-compose.prod.yml"

echo "=== EOP Production 環境設定 ==="

# ---- 1. 取得 RDS Endpoint ----
if [ -n "${RDS_ENDPOINT:-}" ]; then
    DB_HOST="${RDS_ENDPOINT}"
elif [ -f "${ENDPOINT_FILE}" ]; then
    DB_HOST=$(cat "${ENDPOINT_FILE}")
else
    read -p "請輸入 RDS Endpoint: " DB_HOST
fi
echo "RDS Endpoint: ${DB_HOST}"

# ---- 2. 取得密碼 ----
if [ -n "${RDS_MASTER_PASSWORD:-}" ]; then
    DB_PASSWORD="${RDS_MASTER_PASSWORD}"
else
    read -s -p "請輸入 RDS 密碼: " DB_PASSWORD
    echo ""
fi

# ---- 3. 讀取現有 .env 中的值（作為預設值）----
if [ ! -f "${ENV_FILE}" ]; then
    echo "❌ 找不到 ${ENV_FILE}，請確認專案目錄正確。"
    exit 1
fi

# Helper: 從 .env 讀取指定 key 的值
get_env_val() {
    local key="$1"
    local default="${2:-}"
    local val
    val=$(grep "^${key}=" "${ENV_FILE}" 2>/dev/null | head -1 | cut -d'=' -f2-)
    echo "${val:-${default}}"
}

# ---- 4. 產生 .env.prod ----
echo ""
echo "產生 ${ENV_PROD_FILE}..."

SECRET_KEY=$(get_env_val "BACKEND_SECRET_KEY" "CHANGE-ME-IN-PRODUCTION")
REDIS_PASSWORD=$(get_env_val "REDIS_PASSWORD" "")
FRONTEND_URL=$(get_env_val "FRONTEND_URL" "http://localhost:4173")
API_URL=$(get_env_val "API_URL" "http://localhost:8001")

# AWS
AWS_ACCESS_KEY_ID=$(get_env_val "AWS_ACCESS_KEY_ID" "")
AWS_SECRET_ACCESS_KEY=$(get_env_val "AWS_SECRET_ACCESS_KEY" "")
AWS_REGION=$(get_env_val "AWS_REGION" "ap-northeast-1")
AWS_S3_BUCKET=$(get_env_val "AWS_S3_BUCKET" "cms-user-uploads")

cat > "${ENV_PROD_FILE}" <<ENVEOF
############
# Production Environment
# Generated by deploy/03-setup-env.sh
############

# Database (RDS)
DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@${DB_HOST}:5432/postgres

# Backend
BACKEND_APP_NAME=Education Management System
BACKEND_APP_ENV=production
BACKEND_DEBUG=false
BACKEND_SECRET_KEY=${SECRET_KEY}
BACKEND_PORT=8001
BACKEND_COOKIE_DOMAIN=${BACKEND_COOKIE_DOMAIN:-localhost}
BACKEND_COOKIE_SECURE=true
BACKEND_COOKIE_SAMESITE=lax
SESSION_EXPIRE_MINUTES=1440
ACCESS_TOKEN_EXPIRE_MINUTES=15
REFRESH_TOKEN_EXPIRE_DAYS=7

# Redis
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_PORT=6379

# AWS S3
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
AWS_REGION=${AWS_REGION}
AWS_S3_BUCKET=${AWS_S3_BUCKET}

# Frontend
FRONTEND_URL=${FRONTEND_URL}
FRONTEND_PORT=4173
API_URL=${API_URL}
ENVEOF

echo "   已產生 .env.prod"
echo ""
echo "   ⚠️  請手動編輯以下欄位："
echo "   - BACKEND_SECRET_KEY（改為安全的隨機值）"
echo "   - BACKEND_COOKIE_DOMAIN（改為你的 domain）"
echo "   - FRONTEND_URL（改為正式 URL）"
echo "   - API_URL（改為正式 backend URL）"
echo "   - 如需 LINE / Zoom 設定，請手動加入"

# ---- 5. 產生 docker-compose.prod.yml ----
echo ""
echo "產生 ${COMPOSE_PROD_FILE}..."

cat > "${COMPOSE_PROD_FILE}" <<'COMPOSEEOF'
# Production Docker Compose — 連接 AWS RDS
# 用法: docker compose -f docker-compose.prod.yml --env-file .env.prod up --build -d

services:

  backend:
    container_name: teaching-platform-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_started
    environment:
      APP_NAME: ${BACKEND_APP_NAME:-Education Management System}
      APP_ENV: ${BACKEND_APP_ENV:-production}
      DEBUG: ${BACKEND_DEBUG:-false}
      SECRET_KEY: ${BACKEND_SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: redis://redis:6379/0
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      COOKIE_DOMAIN: ${BACKEND_COOKIE_DOMAIN:-localhost}
      COOKIE_SECURE: ${BACKEND_COOKIE_SECURE:-true}
      COOKIE_SAMESITE: ${BACKEND_COOKIE_SAMESITE:-lax}
      SESSION_EXPIRE_MINUTES: ${SESSION_EXPIRE_MINUTES:-1440}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-15}
      REFRESH_TOKEN_EXPIRE_DAYS: ${REFRESH_TOKEN_EXPIRE_DAYS:-7}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_REGION: ${AWS_REGION:-ap-northeast-1}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET:-teaching-platform-contracts}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:4173}
    ports:
      - ${BACKEND_PORT:-8001}:8000
    restart: unless-stopped

  redis:
    container_name: teaching-platform-redis
    image: redis:7-alpine
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  frontend-demo:
    container_name: teaching-platform-frontend-demo
    build:
      context: ./frontend-dennis
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${API_URL:-http://localhost:8001}
    depends_on:
      backend:
        condition: service_started
    ports:
      - ${FRONTEND_PORT:-4173}:3000
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  redis-data:
COMPOSEEOF

echo "   已產生 docker-compose.prod.yml"

echo ""
echo "=== 完成 ==="
echo ""
echo "已產生："
echo "  - .env.prod"
echo "  - docker-compose.prod.yml"
echo ""
echo "下一步: ./deploy/04-start-services.sh"
