export const CONTRACT_STATUS = {
    ACTIVE: 'active',
    SUSPENDED: 'suspended',
    EXPIRED: 'expired',
    PENDING: 'pending',
    TERMINATED: 'terminated'
} as const

export const CONTRACT_DETAIL_TYPE = {
    LESSON_PRICE: 'lesson_price',
    DISCOUNT: 'discount',
    COMPENSATION: 'compensation'
} as const

export const STUDENT_CONTRACT_STATUS_VALUES = [
    CONTRACT_STATUS.PENDING,
    CONTRACT_STATUS.ACTIVE,
    CONTRACT_STATUS.EXPIRED,
    CONTRACT_STATUS.TERMINATED,
    CONTRACT_STATUS.SUSPENDED
] as const;

export const TEACHER_CONTRACT_STATUS_VALUES = [
    CONTRACT_STATUS.PENDING,
    CONTRACT_STATUS.ACTIVE,
    CONTRACT_STATUS.EXPIRED,
    CONTRACT_STATUS.TERMINATED
] as const;
